### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mimipeshy** [e71az/tic-tac-toe#4]
Hi Elias!!!!
I think you have done an amazing job with the project. It's working well for most parts hehehehe, now lets make it perfect

-  After a user inputs their name, you can assign them a symbol

-  Give descriptive error messages especially when a user gives an input that is outside the given scope

-  Validate user names, give them a max length and ensure no empty strings are given as input

-  Try and avoid alot of puts in the main file

-  You can use gems to make your outputs pretty

-  Make use of ruby center method to align your board arrays

- Fix the broken parts of your code :smile: 

- (Optional) You can render the board back once a game is over

Happy coding :smile:  :computer:  :100: 

KInd Regards
Peris Ndanu

**Comment by eliasecasta** [comment]
Thank you Peris!
